### ISSUE TITLE
Can't compile in Delphi 10.2

### ISSUE THREAD

**Issue by raelb** [Alexey-T/ATButtons#72]
Hi,

I'm trying to compile/install into Delphi 10.2
I get the following errors:

[dcc32 Error] atlistbox.pas(488): E2010 Incompatible types: 'TRect' and 'Integer'
[dcc32 Error] atlistbox.pas(488): E2034 Too many actual parameters
[dcc32 Error] atlistbox.pas(559): E2010 Incompatible types: 'TRect' and 'Integer'
[dcc32 Error] atlistbox.pas(559): E2034 Too many actual parameters
[dcc32 Fatal Error] atflatcontrols_register.pas(14): F2063 Could not compile used unit 'atlistbox.pas'

I'm using the latest source

**Comment by Alexey-T** [comment]
I don't have Delphi 10.2 , so trying to fix it just in FreePascal. fix made, OK now?

**Comment by raelb** [comment]
Thanks, it works now
